basePath: /api/v1
definitions:
  dto.CommonDto:
    properties:
      message:
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact:
    email: 1014007642@qq.com
    name: yzy
    url: https://www.yucoding.club
  description: 基于区块链的煤炭大数据物流平台的后端接口文档
  title: 2508yyds队后端接口文档
  version: "1.0"
paths:
  /auth/info:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 获取个人信息
      tags:
      - 用户管理
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 手机号
        in: query
        name: telephone
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 用户登录
      tags:
      - 用户管理
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 电话号码
        in: query
        name: telephone
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: 权限级别 2.煤炭场 3.普通用户
        in: query
        name: kind
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 用户注册
      tags:
      - 用户管理
  /cer/GetAllCer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 获取所有证书
      tags:
      - 接口类别
  /cer/GetOneCer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 煤炭场公钥
        in: query
        name: coalPublicKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 获取一个证书
      tags:
      - 接口类别
  /cer/approvalCer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 煤炭场公钥
        in: query
        name: coalPublicKey
        required: true
        type: string
      - description: 秘钥
        in: query
        name: coalName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 审批证书
      tags:
      - 证书管理
  /cer/registerCer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 注册证书
      tags:
      - 证书管理
  /cer/revokeCer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 煤炭场公钥
        in: query
        name: coalPublicKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 撤销证书
      tags:
      - 接口类别
  /chain/invoke:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 方法名
        in: query
        name: name
        required: true
        type: string
      - description: 参数json
        in: query
        name: args
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 调用链码
      tags:
      - 链码相关
  /chain/query:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 方法名
        in: query
        name: name
        required: true
        type: string
      - description: 参数列表
        in: query
        items:
          type: string
        name: args
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 调用链码
      tags:
      - 链码相关
  /coal/GetGenElectricityUse:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 发电用煤数据
      tags:
      - 煤炭使用数据管理
  /coal/GetOneTx:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 煤炭场名字
        in: query
        name: coalName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 查看一个煤炭场的交易记录
      tags:
      - 煤炭场使用数据管理
  /coal/getAllBalance:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 获取所有煤炭场的煤炭余量
      tags:
      - 煤炭场数据管理
  /coal/getAllUse:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 查看所有煤炭使用数据
      tags:
      - 煤炭使用数据管理
  /coal/getOneBalance:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 煤炭场名字
        in: query
        name: coalName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 获取一个煤炭场的余量
      tags:
      - 煤炭场数据管理
  /index/DestroyIndex:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 煤炭场名字
        in: query
        name: coalName
        required: true
        type: string
      - description: 指标数量
        in: query
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 删除某个煤炭场的指标
      tags:
      - 指标管理
  /index/UseIndex:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 使用人名字
        in: query
        name: coalName
        required: true
        type: string
      - description: 使用方法
        in: query
        name: coalName
        required: true
        type: string
      - description: 指标数量
        in: query
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 使用指标
      tags:
      - 指标管理
  /index/transferIndex:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 起点名字
        in: query
        name: from
        required: true
        type: string
      - description: 终点名字
        in: query
        name: to
        required: true
        type: string
      - description: 指标数量
        in: query
        name: num
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 转移指标
      tags:
      - 指标管理
swagger: "2.0"
