basePath: /api/v1
definitions:
  dto.CommonDto:
    properties:
      message:
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact:
    email: 1014007642@qq.com
    name: yzy
    url: https://www.yucoding.club
  description: 基于区块链的煤炭大数据物流平台的后端接口文档
  title: 2508yyds队后端接口文档
  version: "1.0"
paths:
  /auth/info:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 获取个人信息
      tags:
      - 接口类别
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 手机号
        in: query
        name: telephone
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 用户登录
      tags:
      - 用户管理
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: query
        name: name
        required: true
        type: string
      - description: 电话号码
        in: query
        name: telephone
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 用户注册
      tags:
      - 用户管理
  /coal/getAllBalance:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 获取所有煤炭场的煤炭余量
      tags:
      - 煤炭场数据管理
  /coal/getOneBalance:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 煤炭场名字
        in: query
        name: coalName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 获取一个煤炭场的余量
      tags:
      - 煤炭场数据管理
  /posts2:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 煤炭场名字
        in: query
        name: coalName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 政府发放指标
      tags:
      - 指标发放管理
  /use/GetGenElectricityUse:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 发电用煤数据
      tags:
      - 煤炭使用数据管理
  /use/getAllUse:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CommonDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.CommonDto'
      summary: 查看所有煤炭使用数据
      tags:
      - 煤炭使用数据管理
swagger: "2.0"
